---
- name: Install and configure nginx
  hosts: web
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    
    - name: Install postgresql
      apt:
        name: postgresql-client-14
        state: present        
        
        
